---
apiVersion: v1
kind: Namespace
metadata:
  name:  resource-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-operator-config
  namespace: resource-operator
  labels:
    app: resource-operator
data:
  limits.memory: ''
  limits.cpu: ''
  req.memory: ''
  req.cpu: ''
  max.memory: ''
  max.cpu: ''
  type: ''
  exclude_ns: ''

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-operator
  namespace: resource-operator
spec:
  selector:
    matchLabels:
      app: resource-operator
  template:
    metadata:
      labels:
        app: resource-operator
    spec:
      serviceAccount: resource-operator
      containers:
      - name: resource-operator
        image: timmiles/resourcesoperator:0.1.0
        resources:
          limits:
            memory: "50Mi"
            cpu: "10m"
          requests:
            memory: "50Mi"
            cpu: "10m"
        env:
          - name: MEMORY
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: limits.memory
          - name: CPU
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: limits.cpu
          - name: MEMORY_REQ
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: req.memory
          - name: CPU_REQ
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: req.cpu
          - name: MEMORY_MAX
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: max.memory
          - name: CPU_MAX
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: max.cpu
          - name: TYPE
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: type
          - name: EXCLUDE_NS
            valueFrom:
              configMapKeyRef:
                name: resource-operator-config
                key: exclude_ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-operator
  namespace: resource-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-operator
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["limitranges"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-operator
subjects:
  - kind: ServiceAccount
    name: resource-operator
    namespace: resource-operator