apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    resource-operator.limits/type: 'Container'
    resource-operator.limits/memory: '100Mi'
    resource-operator.limits/cpu: '100m'
    # resource-operator.limits/memory-requests: '500Mi' 
    # resource-operator.limits/cpu-requests: '50m'
    # resource-operator.limits/max-memory: '500Mi'
    # resource-operator.limits/max-cpu: '50m'
    # resource-operator/disabled: 'true'
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
  labels:
    name: test
spec:
  containers:
  - name: test
    image: nginx
